name: Android CI
on:
  pull_request:
    branches: [ main ]

jobs:
  static-analysis:
    name: Static Analysis
    runs-on: ubuntu-latest
    strategy:
      matrix:
        task: [lint, detekt, ktlintCheck]
      fail-fast: false
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
        
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3
      with:
        cache-read-only: ${{ github.event_name == 'pull_request' }}
        
    - name: Grant Gradle wrapper permission
      run: chmod +x ./gradlew
      
    - name: Run ${{ matrix.task }}
      run: ./gradlew ${{ matrix.task }} --build-cache --configuration-cache --daemon --parallel --max-workers=4
      
  test:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
        
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3
      with:
        cache-read-only: ${{ github.event_name == 'pull_request' }}
        
    - name: Grant Gradle wrapper permission
      run: chmod +x ./gradlew
      
    - name: Run Unit Tests
      run: ./gradlew testDebugUnitTest --build-cache --configuration-cache --daemon --parallel --max-workers=4
      
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
        
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3
      with:
        cache-read-only: ${{ github.event_name == 'pull_request' }}
        
    - name: Grant Gradle wrapper permission
      run: chmod +x ./gradlew
      
    - name: Build Project
      run: ./gradlew assembleDebug --build-cache --configuration-cache --daemon --parallel --max-workers=4