name: Android CI

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build & Verify
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Cache Gradle
      uses: actions/cache@v3
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}

    - name: Grant Gradle wrapper permission
      run: chmod +x ./gradlew

    - name: Run Lint
      run: ./gradlew lint

    - name: Run Unit Tests
      run: ./gradlew testDebugUnitTest

    - name: Run Detekt
      run: ./gradlew detekt

    - name: Run Ktlint
      run: ./gradlew ktlintCheck

    - name: Build Project
      run: ./gradlew assembleDebug
